
spring:
  application:
    name: DCSA-Backend
  r2dbc:
    url: r2dbc:postgresql://localhost:5433
    name: dcsa_tnt_v1
    properties:
      schema: dcsa_v1.2
    username: postgres
    password: admin
    initialization-mode: always

server:
  port: 9090

logging:
  level:
    dk: DEBUG

