
spring:
  application:
    name: DCSA-Backend
  r2dbc:
    url: r2dbc:postgresql://127.0.0.53:5432
    name: dcsa_openapi
    properties:
      schema: dcsa_v1_1
    username: dcsa_db_owner
    password: 9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5
    initialization-mode: always

server:
  port: 9090

logging:
  level:
    dk: DEBUG

