
spring:
  application:
    name: DCSA-Backend
  r2dbc:
    url: r2dbc:postgresql://postgres:5432
    name: dcsa_openapi
    properties:
      schema: dcsa_v1_1
    username: postgres
    password: postgres
    initialization-mode: always

server:
  port: 9090

logging:
  level:
    dk: DEBUG

