name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          server-username: ${{ secrets.READ_REPO_USER }}
          server-password: ${{ secrets.MANAGE_PACKAGES_PAT }}
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          repositories: '[{ "id": "github", "name": "DCSA Backend repo", "url": "https://maven.pkg.github.com/dcsaorg/DCSA-Backend", "releases": { "enabled": "false" }, "snapshots": { "enabled": "true" } }]'
          servers: '[{ "id": "github", "username": "AsgerStage", "password": "${{ secrets.AS_PACKAGES_PAT }}" }]'    
      - run: cat /home/runner/.m2/settings.xml    
      - name: Publish package
        run: mvn -B deploy -DskipTests
