# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
     # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie 
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
      # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
        java-version: 11        
       # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
    - name: Install dependencies
      run: npm i pg && apt-get update && apt-get install maven  
    - name: Connect to PostgreSQL
      # Runs a script that creates a PostgreSQL client, populates
      # the client with data, and retrieves data
      run: node dbsetup.js
      # Environment variable used by the `client.js` script to create
      # a new PostgreSQL client.
      env:
        # The hostname used to communicate with the PostgreSQL service container
        POSTGRES_HOST: postgres
        # The default PostgreSQL port
        POSTGRES_PORT: 5432
        
    - name: list dirs
      run: ls -a
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run backend
      run: java -jar target/dcsa_backend*.war &
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        repository: dcsaorg/DCSA-API-Validator
        ref: master
        token: ${{ secrets.read_repo_pat }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
