# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
      # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
        java-version: 11        
    - name: list dirs
      run: ls -a
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Setup PostgreSQL With Init Scripts
      uses: m4nu56/postgresql-action@1.0
      with:
        postgresql password: ${{ secrets.psql_pw }}
        postgresql init scripts: src/main/resources/datamodel   
        
    - name: Run SQL scripts
      run: psql -c "BEGIN TRANSACTION;" -f 001.sql -f 002.sql -f 003.sql -f 004.sql -c "COMMIT;"
    - name: Run backend
      run: java -jar target/dcsa_backend*.war &
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        repository: dcsaorg/DCSA-API-Validator
        ref: master
        token: ${{ secrets.read_repo_pat }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
