name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          server-username: ${{ secrets.READ_REPO_USER }}
          server-password: ${{ secrets.MANAGE_PACKAGES_PAT }}
      - name: Publish package
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.READ_REPO_USER }}
          MAVEN_PASSWORD: ${{ secrets.MANAGE_PACKAGES_PAT }}
